appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: MohZ3x55bi841VP89RraLOJNy0lfyyBlE92utkju4Tg7rHtM3mUGSsSVij4CaATplrUpvCRcm4mdqljN+m61PZLvR0HeYoLZpLHcZL2EOtRw0eNk3JhwmC0hzAv0UbWUHZIeHmpd6PtWE7INCwGGITtvGteVEQ84bw1XmZ3Ri3wJiC4fORNMBTGFPo9cK3uWDkQOolP18SOSMRtPHG9dvT7UkUahTpMAFGTJoWOWHO9YSbDyDupsg8HHQmkAmAwq3RrRnurgtn3hJ73VIXFTi4pQwwAX8jn+qFISsapBI+EERRuGpINX1yzt2STVbVO+pETClUOo5gmsrjWyRyp0Wxi5N6Ju7y6WS3akEBvqtQHNwLQFQcd4XWQ/IFhkUCDy2kM2gfyhzwUE11aeZslQn1O5ZZVZPZnP1oOOoiFIH0seVaO64l948SwtI6upr7+jY6ibulRS11wVdNZ3wiug0TrKLp/1IA5yrtcvs2h2TO30FbB3RGfQoLNFPczrq5LGzXi3YnfF+EUu88hK7k0zXI5YLKEQuTOPRSecXSvo1D9GV+gWvLbn8O/RMzKoPaTFoWAVm6KMIciuncMQc6IbSWhOE8JtZU5rlWv10WO7qWK+QEaHPN9TyGOy2T3wqCJf4CLMmnM0RqNSO8MQT8VoICLwo2AAWz5CuhZBRV2qQWQ=
